server:
  port: 8080

spring:
  application:
    name: loja-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/loja
    username: loja
    password: loja
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/loja

---
spring:
  config:
    activate:
      on-profile: hml
  datasource:
    url: jdbc:postgresql://db:5432/loja
    username: loja
    password: loja
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/loja
